"""Registry of the CaLab web apps the Python bridge can launch.

Every per-app fact the bridge needs lives in one :class:`AppSpec` entry here:
where the app is deployed, which result schema it sends back, which binary
arrays (if any) it uploads alongside that JSON, and how to turn the raw payload
into the value the Python caller gets. The HTTP server
(:mod:`._server`) and the orchestrator (:func:`._apps.launch`) are generic and
read everything from the entry, so wiring up a new app is one entry in
:data:`APPS` -- no new endpoint, event, or orchestrator.

Keys are lowercase app slugs (``catune``, ``cadecon``, ``carank``), the same
slugs as ``calab.id`` in ``apps/*/package.json``.

Where an app lives is also published by the deployed site in ``apps.json``
(:mod:`._manifest`, generated by ``scripts/combine-dist.mjs``).
:func:`resolve_app` overlays that manifest on these entries, so a pinned
``calab`` follows a renamed path and can open apps added after its release;
the built-in path segments below are the offline fallback. The result schema
is never taken from the manifest: it stays here, pinned against the
TypeScript sources by ``tests/test_bridge_registry.py``.
"""

from __future__ import annotations

import dataclasses
import re
import urllib.parse
from collections.abc import Callable, Mapping
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

from ._manifest import PAGES_BASE_URL, load_manifest

if TYPE_CHECKING:
    from ._handshake import BridgeResult

#: Path segments of the results routes that are not app slugs. ``activity`` is
#: the legacy CaDecon array route (``POST /api/v1/results/activity``), so no app
#: may use it as a slug.
RESERVED_SLUGS = frozenset({"activity"})

_SLUG_RE = re.compile(r"^[a-z][a-z0-9-]*$")


@dataclass(frozen=True)
class ResultSchema:
    """The result payload an app POSTs back, and the version this package reads.

    ``version`` is the schema version this Python package was written against,
    in whatever form the app sends it (CaTune sends ``"1.2.0"``, CaDecon sends
    the integer ``2``). The handshake compares majors: a different major is
    rejected, a different minor/patch is accepted with a warning.
    """

    name: str
    version: str | int
    version_field: str = "schema_version"


#: Signature of a per-app post-processing hook: ``(result, fs) -> value``,
#: where ``fs`` is the sampling rate the caller passed in.
PostProcess = Callable[["BridgeResult", float], Any]


@dataclass(frozen=True)
class AppSpec:
    """Everything the bridge needs to know about one web app.

    Attributes
    ----------
    slug
        Lowercase registry key; also the ``{app}`` in
        ``POST /api/v1/results/{app}``.
    display_name
        Human-readable name used in terminal messages.
    path_segment
        GitHub Pages path segment (case-sensitive, as deployed).
    result_schema
        The result payload the app sends back, or ``None`` if the app cannot
        export to the bridge yet (it can still be resolved to a URL).
    arrays
        Names of ``.npy`` arrays the app POSTs to
        ``/api/v1/results/{app}/{name}`` *before* its JSON results. The JSON
        POST is the completion signal.
    legacy_result_paths
        Pre-registry routes this app's deployed builds still POST their JSON
        results to. Kept so the live apps keep working unchanged; new apps
        should use only the generic route.
    postprocess
        Hook turning the raw :class:`BridgeResult` into the value returned to
        the caller. ``None`` returns the :class:`BridgeResult` itself.
    base_url
        Site root ``path_segment`` is relative to: :data:`PAGES_BASE_URL`, or
        the directory the manifest was fetched from.
    registered
        ``False`` for an app known only from the deployed manifest: it has a
        URL but this ``calab`` does not know its results format.
    """

    slug: str
    display_name: str
    path_segment: str
    result_schema: ResultSchema | None
    arrays: tuple[str, ...] = ()
    legacy_result_paths: tuple[str, ...] = ()
    postprocess: PostProcess | None = field(default=None, compare=False)
    base_url: str = PAGES_BASE_URL
    registered: bool = True

    @property
    def default_url(self) -> str:
        """The app's deployed URL."""
        return urllib.parse.urljoin(self.base_url, f"{self.path_segment}/")

    @property
    def result_path(self) -> str:
        """Generic route the app POSTs its JSON results to."""
        return f"/api/v1/results/{self.slug}"

    def array_path(self, name: str) -> str:
        """Generic route the app POSTs the ``.npy`` array *name* to."""
        return f"{self.result_path}/{name}"


def _validate(apps: Mapping[str, AppSpec]) -> None:
    for key, spec in apps.items():
        if key != spec.slug:
            raise ValueError(f"registry key {key!r} does not match slug {spec.slug!r}")
        if not _SLUG_RE.match(spec.slug):
            raise ValueError(f"app slug {spec.slug!r} must be lowercase [a-z0-9-]")
        if spec.slug in RESERVED_SLUGS:
            raise ValueError(f"app slug {spec.slug!r} is reserved")
        if spec.result_schema is None and (spec.arrays or spec.legacy_result_paths):
            raise ValueError(f"app {spec.slug!r} declares bridge routes but no result schema")


def _postprocess_catune(result: BridgeResult, fs: float) -> dict:
    from ._postprocess import catune_params

    return catune_params(result, fs)


def _postprocess_cadecon(result: BridgeResult, fs: float) -> Any:
    from ._postprocess import cadecon_result

    return cadecon_result(result, fs)


APPS: dict[str, AppSpec] = {
    spec.slug: spec
    for spec in (
        AppSpec(
            slug="catune",
            display_name="CaTune",
            path_segment="CaTune",
            # packages/io/src/export.ts `buildExportData`
            result_schema=ResultSchema(name="catune-export", version="1.2.0"),
            legacy_result_paths=("/api/v1/params",),
            postprocess=_postprocess_catune,
        ),
        AppSpec(
            slug="cadecon",
            display_name="CaDecon",
            path_segment="CaDecon",
            # apps/cadecon/src/lib/export-utils.ts `buildCaDeconResultsPayload`
            result_schema=ResultSchema(name="cadecon-results", version=2),
            arrays=("activity",),
            legacy_result_paths=("/api/v1/results",),
            postprocess=_postprocess_cadecon,
        ),
        AppSpec(
            slug="carank",
            display_name="CaRank",
            path_segment="CaRank",
            # CaRank has no bridge export yet.
            result_schema=None,
        ),
    )
}
_validate(APPS)


def get_app(slug: str) -> AppSpec:
    """Look up an app in the built-in registry by slug (case-insensitive).

    Never touches the network; :func:`resolve_app` adds the deployed manifest.

    Raises
    ------
    ValueError
        If *slug* is not a registered app.
    """
    spec = APPS.get(slug.lower())
    if spec is None:
        known = ", ".join(sorted(APPS))
        raise ValueError(
            f"unknown CaLab app {slug!r}; known apps: {known}. If it is a newer app, "
            "upgrade calab: pip install --upgrade calab"
        )
    return spec


def resolve_app(slug: str) -> AppSpec:
    """Look up an app, taking its location from the deployed manifest.

    - Listed in the manifest and the registry: the registry entry with the
      manifest's path segment, display name and site root.
    - Only in the registry (offline, fetch failed, or a stale manifest that
      omits it): the built-in entry unchanged.
    - Only in the manifest (an app newer than this ``calab``): an entry with
      ``registered=False`` and no result schema, usable for its URL only.

    Raises
    ------
    ValueError
        If neither the registry nor the manifest knows *slug*.
    """
    key = slug.lower()
    builtin = APPS.get(key)
    manifest = load_manifest()
    entry = manifest.apps.get(key) if manifest is not None else None
    if manifest is None or entry is None or key in RESERVED_SLUGS:
        return get_app(slug)
    if builtin is not None:
        return dataclasses.replace(
            builtin,
            display_name=entry.display_name,
            path_segment=entry.path,
            base_url=manifest.base_url,
        )
    return AppSpec(
        slug=key,
        display_name=entry.display_name,
        path_segment=entry.path,
        result_schema=None,
        base_url=manifest.base_url,
        registered=False,
    )


def bridge_app(slug: str, *, app_url: str | None = None) -> AppSpec:
    """The spec :func:`._apps.launch` runs: resolved, and able to use the bridge.

    With an explicit *app_url* the manifest is not consulted (the caller has
    said where the app is), so only built-in apps are accepted.

    Raises
    ------
    ValueError
        If the app is unknown, known only from the manifest (``calab`` is too
        old to read its results), or has no bridge export.
    """
    spec = get_app(slug) if app_url is not None else resolve_app(slug)
    if not spec.registered:
        manifest = load_manifest()
        release = f" (CaLab release {manifest.release})" if manifest and manifest.release else ""
        raise ValueError(
            f"{spec.display_name} ({spec.slug!r}) is published on the CaLab site{release}, "
            "but this version of calab does not know its results format. "
            "Upgrade calab: pip install --upgrade calab"
        )
    if spec.result_schema is None:
        raise ValueError(f"{spec.display_name} does not support the Python bridge yet")
    return spec


def app_url(slug: str) -> str:
    """Deployed URL of the app *slug*, from the site's manifest when available."""
    return resolve_app(slug).default_url
