name: Bug Report
description: Report something that isn't working correctly in CaLab
title: '[Bug] '
labels: ['bug']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened, and what did you expect instead?
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: >
        Optional. Steps to reproduce the behavior.
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error
    validations:
      required: false

  - type: input
    id: browser-os
    attributes:
      label: Browser / OS
      description: >
        Optional. e.g. Chrome 120 on macOS 14, Firefox on Ubuntu 22.04
      placeholder: e.g. Chrome 120 / macOS 14
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: >
        Optional. Screenshots, console errors, or other details.
    validations:
      required: false
