name: General Feedback
description: Share thoughts, suggestions, or general feedback about CaTune
title: "[Feedback] "
labels: ["feedback"]
body:
  - type: textarea
    id: feedback
    attributes:
      label: Feedback
      description: What would you like to share?
      placeholder: Your feedback here...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: >
        Optional. Screenshots, links, or other context that helps
        explain your feedback.
    validations:
      required: false
