-- Seed data for field_options table
-- Safe to re-run: uses ON CONFLICT DO NOTHING

INSERT INTO field_options (field_name, value, display_order) VALUES
  ('indicator', 'GCaMP6f (AAV)', 0),
  ('indicator', 'GCaMP6f (transgenic)', 1),
  ('indicator', 'GCaMP6m (AAV)', 2),
  ('indicator', 'GCaMP6m (transgenic)', 3),
  ('indicator', 'GCaMP6s (AAV)', 4),
  ('indicator', 'GCaMP6s (transgenic)', 5),
  ('indicator', 'GCaMP7f (AAV)', 6),
  ('indicator', 'GCaMP7f (transgenic)', 7),
  ('indicator', 'GCaMP7s (AAV)', 8),
  ('indicator', 'jGCaMP8f (AAV)', 9),
  ('indicator', 'jGCaMP8m (AAV)', 10),
  ('indicator', 'jGCaMP8s (AAV)', 11),
  ('indicator', 'GCaMP8f (AAV)', 12),
  ('indicator', 'GCaMP8m (AAV)', 13),
  ('indicator', 'GCaMP8s (AAV)', 14),
  ('indicator', 'RCaMP1h (AAV)', 15),
  ('indicator', 'RCaMP2 (AAV)', 16),
  ('indicator', 'jRGECO1a (AAV)', 17),
  ('indicator', 'jRGECO1b (AAV)', 18),
  ('indicator', 'XCaMP-G (AAV)', 19),
  ('indicator', 'XCaMP-R (AAV)', 20),
  ('indicator', 'GCaMP-X (AAV)', 21),
  ('indicator', 'CaMPARI2 (AAV)', 22),
  ('indicator', 'NIR-GECO1 (AAV)', 23),
  ('indicator', 'OGB-1 (dye)', 24),
  ('indicator', 'OGB-2 (dye)', 25),
  ('indicator', 'Cal-520 (dye)', 26),
  ('indicator', 'Cal-590 (dye)', 27),
  ('indicator', 'Fluo-4 (dye)', 28),
  ('indicator', 'Fluo-8 (dye)', 29),
  ('indicator', 'Fura-2 (dye)', 30),
  ('indicator', 'Rhod-2 (dye)', 31),
  ('indicator', 'X-Rhod-1 (dye)', 32)
ON CONFLICT DO NOTHING;

INSERT INTO field_options (field_name, value, display_order) VALUES
  ('species', 'mouse', 0),
  ('species', 'rat', 1),
  ('species', 'zebrafish', 2),
  ('species', 'zebrafish larva', 3),
  ('species', 'drosophila', 4),
  ('species', 'C. elegans', 5),
  ('species', 'macaque', 6),
  ('species', 'marmoset', 7),
  ('species', 'ferret', 8),
  ('species', 'cat', 9),
  ('species', 'human (slice)', 10),
  ('species', 'human (organoid)', 11),
  ('species', 'guinea pig', 12),
  ('species', 'hamster', 13),
  ('species', 'rabbit', 14),
  ('species', 'songbird', 15),
  ('species', 'xenopus', 16),
  ('species', 'lamprey', 17),
  ('species', 'planarian', 18)
ON CONFLICT DO NOTHING;

INSERT INTO field_options (field_name, value, display_order) VALUES
  ('brain_region', 'cortex', 0),
  ('brain_region', 'cortex — prefrontal (PFC)', 1),
  ('brain_region', 'cortex — motor (M1)', 2),
  ('brain_region', 'cortex — premotor (M2)', 3),
  ('brain_region', 'cortex — somatosensory (S1)', 4),
  ('brain_region', 'cortex — barrel cortex (S1BF)', 5),
  ('brain_region', 'cortex — visual (V1)', 6),
  ('brain_region', 'cortex — auditory (A1)', 7),
  ('brain_region', 'cortex — retrosplenial (RSC)', 8),
  ('brain_region', 'cortex — entorhinal (EC)', 9),
  ('brain_region', 'cortex — piriform', 10),
  ('brain_region', 'cortex — insular', 11),
  ('brain_region', 'cortex — cingulate (ACC)', 12),
  ('brain_region', 'cortex — orbitofrontal (OFC)', 13),
  ('brain_region', 'cortex — parietal', 14),
  ('brain_region', 'hippocampus', 15),
  ('brain_region', 'hippocampus — CA1', 16),
  ('brain_region', 'hippocampus — CA2', 17),
  ('brain_region', 'hippocampus — CA3', 18),
  ('brain_region', 'hippocampus — dentate gyrus (DG)', 19),
  ('brain_region', 'hippocampus — subiculum', 20),
  ('brain_region', 'striatum', 21),
  ('brain_region', 'striatum — dorsal (dSTR)', 22),
  ('brain_region', 'striatum — dorsomedial (DMS)', 23),
  ('brain_region', 'striatum — dorsolateral (DLS)', 24),
  ('brain_region', 'striatum — ventral / NAc', 25),
  ('brain_region', 'NAc — core', 26),
  ('brain_region', 'NAc — shell', 27),
  ('brain_region', 'globus pallidus', 28),
  ('brain_region', 'thalamus', 29),
  ('brain_region', 'thalamus — lateral geniculate (LGN)', 30),
  ('brain_region', 'thalamus — medial geniculate (MGN)', 31),
  ('brain_region', 'thalamus — ventral posteromedial (VPM)', 32),
  ('brain_region', 'thalamus — mediodorsal (MD)', 33),
  ('brain_region', 'thalamus — reticular (TRN)', 34),
  ('brain_region', 'VTA', 35),
  ('brain_region', 'substantia nigra (SNc)', 36),
  ('brain_region', 'substantia nigra (SNr)', 37),
  ('brain_region', 'superior colliculus', 38),
  ('brain_region', 'inferior colliculus', 39),
  ('brain_region', 'periaqueductal gray (PAG)', 40),
  ('brain_region', 'cerebellum', 41),
  ('brain_region', 'cerebellum — Purkinje cells', 42),
  ('brain_region', 'cerebellum — granule cells', 43),
  ('brain_region', 'cerebellum — deep cerebellar nuclei', 44),
  ('brain_region', 'hypothalamus', 45),
  ('brain_region', 'hypothalamus — arcuate (ARC)', 46),
  ('brain_region', 'hypothalamus — lateral (LH)', 47),
  ('brain_region', 'hypothalamus — paraventricular (PVN)', 48),
  ('brain_region', 'hypothalamus — ventromedial (VMH)', 49),
  ('brain_region', 'hypothalamus — suprachiasmatic (SCN)', 50),
  ('brain_region', 'amygdala', 51),
  ('brain_region', 'amygdala — basolateral (BLA)', 52),
  ('brain_region', 'amygdala — central (CeA)', 53),
  ('brain_region', 'amygdala — medial (MeA)', 54),
  ('brain_region', 'brainstem', 55),
  ('brain_region', 'locus coeruleus (LC)', 56),
  ('brain_region', 'dorsal raphe (DRN)', 57),
  ('brain_region', 'parabrachial nucleus', 58),
  ('brain_region', 'nucleus tractus solitarius (NTS)', 59),
  ('brain_region', 'olfactory bulb', 60),
  ('brain_region', 'bed nucleus of stria terminalis (BNST)', 61),
  ('brain_region', 'spinal cord', 62),
  ('brain_region', 'retina', 63),
  ('brain_region', 'habenula', 64),
  ('brain_region', 'septum', 65),
  ('brain_region', 'claustrum', 66)
ON CONFLICT DO NOTHING;

INSERT INTO field_options (field_name, value, display_order) VALUES
  ('microscope_type', '1-photon widefield', 0),
  ('microscope_type', '1-photon miniscope', 1),
  ('microscope_type', '2-photon', 2),
  ('microscope_type', '3-photon', 3),
  ('microscope_type', 'confocal', 4),
  ('microscope_type', 'spinning disk confocal', 5),
  ('microscope_type', 'light-sheet', 6),
  ('microscope_type', 'fiber photometry', 7)
ON CONFLICT DO NOTHING;

INSERT INTO field_options (field_name, value, display_order) VALUES
  ('cell_type', 'excitatory neuron', 0),
  ('cell_type', 'inhibitory neuron', 1),
  ('cell_type', 'pyramidal cell', 2),
  ('cell_type', 'interneuron — PV+', 3),
  ('cell_type', 'interneuron — SST+', 4),
  ('cell_type', 'interneuron — VIP+', 5),
  ('cell_type', 'medium spiny neuron (MSN)', 6),
  ('cell_type', 'D1 MSN', 7),
  ('cell_type', 'D2 MSN', 8),
  ('cell_type', 'dopaminergic neuron', 9),
  ('cell_type', 'serotonergic neuron', 10),
  ('cell_type', 'cholinergic neuron', 11),
  ('cell_type', 'Purkinje cell', 12),
  ('cell_type', 'granule cell', 13),
  ('cell_type', 'astrocyte', 14),
  ('cell_type', 'microglia', 15),
  ('cell_type', 'oligodendrocyte', 16)
ON CONFLICT DO NOTHING;
