/**
 * WASM ↔ native parity: the browser build of the solver must reproduce the
 * golden fixtures produced by the native Rust build.
 *
 * Fixtures live in python/tests/fixtures/ and are generated by
 * crates/solver/tests/generate_fixtures.rs on the native target. Every other
 * TypeScript test mocks the solver; this one loads the real
 * crates/solver/pkg build (wasm-pack --target web) through the production
 * adapter (`initWasm` in wasm-adapter.ts) and replays the generator's exact
 * procedure via the wasm-bindgen `Solver` API.
 *
 * Loading: the `--target web` glue calls `fetch(new URL('calab_solver_bg.wasm',
 * import.meta.url))`. Node's fetch does not serve file: URLs, so the test
 * stubs `fetch` to read that one file from disk and hand it back as an
 * `application/wasm` Response. Everything after that — instantiation, the
 * adapter's idempotent init, the Solver class — is the production path.
 *
 * If pkg/ is missing (it is normally built by the root `pretest` hook), the
 * suite is skipped locally with a message, but fails in CI (`CI` env set) so
 * the check can never silently disappear there.
 */
import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { afterAll, beforeAll, describe, expect, it, vi } from 'vitest';
import { Solver, initWasm } from '../wasm-adapter.ts';

const REPO_ROOT = fileURLToPath(new URL('../../../../', import.meta.url));
const PKG_WASM = `${REPO_ROOT}crates/solver/pkg/calab_solver_bg.wasm`;
const FIXTURES_DIR = `${REPO_ROOT}python/tests/fixtures`;

const FIXTURE_NAMES = [
  'fast_kinetics',
  'high_lambda',
  'standard_clean',
  'standard_dc_offset',
  'with_filter',
] as const;

/** Mirrors `struct Fixture` in generate_fixtures.rs. */
interface Fixture {
  params: { tau_rise: number; tau_decay: number; lambda: number; fs: number };
  trace: number[];
  kernel: number[];
  solution: number[];
  baseline: number;
  reconvolution: number[];
  iterations: number;
  filter_enabled: boolean;
  filtered_trace: number[] | null;
}

// Both builds run the same Rust source in f32, so the expected discrepancy is
// last-ulp noise from platform libm (exp/ln in the kernel and filter) carried
// through the FISTA loop — not the f32-vs-f64 algorithmic divergence that
// python/tests/test_cross_language.py has to tolerate (atol/rtol 1e-2, and
// 0.3/0.4 with the filter). A 1e-4 bound is ~1000 f32 ulps at unit scale:
// loose enough for ulp drift, tight enough that any change to the algorithm,
// defaults or convergence criterion fails.
const ATOL = 1e-4;
const RTOL = 1e-4;

const pkgPresent = existsSync(PKG_WASM);
if (!pkgPresent && process.env.CI) {
  throw new Error(
    `WASM pkg missing at ${PKG_WASM}. Run \`npm run ensure-wasm\` (the root pretest hook) first.`,
  );
}
if (!pkgPresent) {
  console.warn(
    `[wasm-parity] skipped: ${PKG_WASM} not found. Run \`npm run ensure-wasm\` to build it.`,
  );
}

function loadFixture(name: string): Fixture {
  return JSON.parse(readFileSync(`${FIXTURES_DIR}/${name}.json`, 'utf8')) as Fixture;
}

interface DiffReport {
  maxAbs: number;
  maxAbsIndex: number;
  maxRel: number;
  violations: number;
  firstViolation: number;
}

function diff(actual: ArrayLike<number>, expected: ArrayLike<number>): DiffReport {
  const r: DiffReport = {
    maxAbs: 0,
    maxAbsIndex: -1,
    maxRel: 0,
    violations: 0,
    firstViolation: -1,
  };
  for (let i = 0; i < expected.length; i++) {
    const d = Math.abs(actual[i] - expected[i]);
    const scale = Math.abs(expected[i]);
    if (d > r.maxAbs) {
      r.maxAbs = d;
      r.maxAbsIndex = i;
    }
    if (scale > 0) r.maxRel = Math.max(r.maxRel, d / scale);
    if (!(d <= ATOL + RTOL * scale)) {
      if (r.firstViolation < 0) r.firstViolation = i;
      r.violations++;
    }
  }
  return r;
}

function expectClose(
  label: string,
  actual: ArrayLike<number>,
  expected: ArrayLike<number>,
): DiffReport {
  expect(actual.length, `${label}: length`).toBe(expected.length);
  const r = diff(actual, expected);
  const i = r.firstViolation;
  const detail =
    `${label}: max|Δ|=${r.maxAbs.toExponential(3)} at [${r.maxAbsIndex}], ` +
    `max rel=${r.maxRel.toExponential(3)}, ${r.violations}/${expected.length} outside ` +
    `atol=${ATOL} + rtol=${RTOL}·|expected|` +
    (i >= 0 ? `; first at [${i}]: wasm=${actual[i]}, native=${expected[i]}` : '');
  expect(r.violations, detail).toBe(0);
  return r;
}

/**
 * Replays generate_fixtures.rs: set_params → (filter) → set_trace →
 * (apply_filter) → subtract_baseline → step_batch(10) up to 200 times.
 */
function solveLikeGenerator(fx: Fixture) {
  const solver = new Solver();
  try {
    const { tau_rise, tau_decay, lambda, fs } = fx.params;
    solver.set_params(tau_rise, tau_decay, lambda, fs);
    if (fx.filter_enabled) solver.set_filter_enabled(true);
    const kernel = solver.get_kernel();

    solver.set_trace(Float32Array.from(fx.trace));
    let filtered: Float32Array | null = null;
    if (fx.filter_enabled) {
      solver.apply_filter();
      filtered = solver.get_trace();
    }
    solver.subtract_baseline();
    for (let b = 0; b < 200; b++) {
      if (solver.step_batch(10)) break;
    }

    return {
      kernel,
      filtered,
      solution: solver.get_solution(),
      baseline: solver.get_baseline(),
      reconvolution: solver.get_reconvolution_with_baseline(),
      iterations: solver.iteration_count(),
    };
  } finally {
    solver.free();
  }
}

describe.skipIf(!pkgPresent)('WASM solver reproduces native golden fixtures', () => {
  beforeAll(async () => {
    vi.stubGlobal('fetch', async (input: URL | string) => {
      const url = input instanceof URL ? input : new URL(input);
      if (url.protocol !== 'file:') throw new Error(`unexpected fetch in test: ${url}`);
      return new Response(readFileSync(fileURLToPath(url)), {
        headers: { 'Content-Type': 'application/wasm' },
      });
    });
    await initWasm();
  });

  afterAll(() => {
    vi.unstubAllGlobals();
  });

  describe.each(FIXTURE_NAMES)('%s', (name) => {
    const fx = loadFixture(name);
    let out: ReturnType<typeof solveLikeGenerator>;
    beforeAll(() => {
      out = solveLikeGenerator(fx);
    });

    it('kernel', () => {
      expectClose(`${name} kernel`, out.kernel, fx.kernel);
    });

    if (fx.filter_enabled) {
      it('filtered trace', () => {
        expect(fx.filtered_trace, 'fixture has filtered_trace').not.toBeNull();
        expectClose(`${name} filtered_trace`, out.filtered!, fx.filtered_trace!);
      });
    }

    it('iteration count', () => {
      expect(out.iterations, `${name}: iterations (wasm vs native)`).toBe(fx.iterations);
    });

    it('solution', () => {
      expectClose(`${name} solution`, out.solution, fx.solution);
    });

    it('baseline', () => {
      const d = Math.abs(out.baseline - fx.baseline);
      expect(
        d <= ATOL + RTOL * Math.abs(fx.baseline),
        `${name} baseline: wasm=${out.baseline}, native=${fx.baseline}, |Δ|=${d.toExponential(3)}`,
      ).toBe(true);
    });

    it('reconvolution (with baseline)', () => {
      expectClose(`${name} reconvolution`, out.reconvolution, fx.reconvolution);
    });
  });
});
